export const GRAPHQL_ENDPOINT = process.env.REACT_PUBLIC_GRAPHQL_ENDPOINT;
export const GOOGLE_CLIENT_ID = process.env.REACT_PUBLIC_GOOGLE_CLIENT_ID;
export const GOOGLE_WORKSPACE_DOMAIN =
  process.env.REACT_PUBLIC_GOOGLE_WORKSPACE_DOMAIN;

export const HASURA_GRAPHQL_ENDPOINT =
  process.env.REACT_PUBLIC_HASURA_GRAPHQL_ENDPOINT;
export const HASURA_WS_GRAPHQL_ENDPOINT =
  process.env.REACT_PUBLIC_HASURA_WS_GRAPHQL_ENDPOINT;

export const COMPANY_COMMISSION_PERCENTAGE = 8;

export const COMPANY_BLOG_POST_ENDPOINT =
  process.env.REACT_PUBLIC_COMPANY_BLOG_ENDPOINT;

export const CLEARBIT_URL =
  "https://autocomplete.clearbit.com/v1/companies/suggest";
